config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  resources :users, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, presence: true, uniqueness: true
    validates :pass, presence: true, length: {minimum: 4}
    #validates :password, presence: true, confirmation: true
  
    attr_accessor :password, :password_confirmation
  
    #has_many :tweets, dependent: :destroy
    #has_many :likes, dependent: :destroy
    #has_many :like_tweets, through: :likes, source: :tweet

    def self.authenticate(uid, pass)
        user = User.find_by(uid: uid)
        if user and BCrypt::Password.new(user.pass) == pass
            user
        else
            nil
        end
    end
  
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_user
            if session[:login_uid]
                User.find_by(uid: session[:login_uid])
            end
        end
        helper_method :current_user
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def login
        user = User.authenticate(params[:uid], params[:pass])
        if user
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render top_login_path
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        pass = BCrypt::Password.create(params[:user][:pass])
        @user = User.new(uid: params[:user][:uid], pass: pass)
        if @user.save
            flash[:info] = 'ユーザを登録完了しました。'
            redirect_to users_path
        else
            render new_user_path
        end
    end

    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>K56</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/login.html.erb
<h1>ログイン</h1>
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @users.each do |e| %>
<p>
  <%= e.uid %>
  <%= e.pass %>
  <%= link_to '削除', user_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to 'ユーザ登録', new_user_path %></p>

<p><%= link_to '戻る', :back %></p>

app/views/users/index.html.erb
<h1>index</h1>
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>

<% @users.each do |e| %>
<p>
  <%= e.uid %>
  <%= e.pass %>
  <%= link_to '削除', user_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to 'ユーザ登録', new_user_path %></p>

<p><%= link_to '戻る', :back %></p>

app/views/users/new.html.erb
<h1>新規登録</h1>
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, url: {action: :create} do |f| %>
<p>
  <%= f.label :uid, 'ユーザID' %>
  <%= f.text_field :uid %>
</p>
<p>
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>

<p><%= link_to '戻る', :back %>